spring:
    codec:
        max-in-memory-size: 500KB
    data:
        mongodb:
            auto-index-creation: true
web-client:
    response-timeout-ms: 10000

providers:
    provider1: "https://zretmlbsszmm4i35zrihcflchm0ktwwj.lambda-url.eu-central-1.on.aws/provider/flights1"
    provider2: "https://zretmlbsszmm4i35zrihcflchm0ktwwj.lambda-url.eu-central-1.on.aws/provider/flights3"
